/******* THIS FILE WAS AUTO-GENERATED BY SCANOSS MINR *******/
#ifndef _CRYPTO_LOADS_
#define _CRYPTO_LOADS_
#include "trie.h"
extern struct T_TrieNode * root;
void load_default_crypto(void){
}
#endif
