// This file is autogenerated by SCANOSS Minr, available at https://github.com/scanoss/minr

#define MAX_LICENSE_ID 64
#define MAX_LICENSE_TEXT 1024
#define LICENSE_COUNT 103
#include <string.h>

typedef struct normalized_license
{
  char spdx_id[MAX_LICENSE_ID];
  char text[MAX_LICENSE_TEXT];
  int ln;
} normalized_license;

normalized_license licenses[LICENSE_COUNT];

int load_licenses()
{
  strcpy(licenses[0].spdx_id, "EPL-2.0");
  strcpy(licenses[0].text,"eclipsepubliclicensev20");
  licenses[0].ln = 23;

  strcpy(licenses[1].spdx_id, "Unicode-DFS-2016");
  strcpy(licenses[1].text,"unicodeinclicenseagreementdatafilesandsoftwareunicodedatafilesincludealldatafilesunderthedirectorieshttpwwwunicodeorgpublichttpwwwunicodeorgreportshttpwwwunicodeorgcldrdatahttpsourceicuprojectorgreposicuhttpwwwunicodeorgivddataandhttpwwwunicodeorgutilitytracbrowser");
  licenses[1].ln = 265;

  strcpy(licenses[2].spdx_id, "Libpng");
  strcpy(licenses[2].text,"thiscopyofthelibpngnoticesisprovidedforyourconvenienceincaseofanydiscrepancybetweenthiscopyandthenoticesinthefilepnghthatisincludedinthelibpngdistributionthelattershallprevail");
  licenses[2].ln = 175;

  strcpy(licenses[3].spdx_id, "BSD-4-Clause-UC");
  strcpy(licenses[3].text,"theregentsoftheuniversityofcaliforniaallrightsreservedredistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistribution3alladvertisingmaterialsmentioningfeaturesoruseofthissoftwaremustdisplaythefollowingacknowledgementthisproductincludessoftwaredevelopedbytheuniversityofcaliforniaberkeleyanditscontributors4neitherthenameoftheuniversitynorthenamesofitscontributorsmaybeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutspecificpriorwrittenpermissionthissoftwareisprovidedbytheregentsandcontributorsasisandanyexpressorimpliedwarrantiesincludingbutnotlimitedtotheimpliedwarrantiesofmerchantabilityandfitnessforaparticularpurposearedisclaimedinnoeventshalltheregentsorcontributorsbe");
  licenses[3].ln = 1023;

  strcpy(licenses[4].spdx_id, "EFL-2.0");
  strcpy(licenses[4].text,"1permissionisherebygrantedtousecopymodifyandordistributethispackageprovidedthatcopyrightnoticesareretainedunchangedanydistributionofthispackagewhethermodifiedornotincludesthislicensetext2permissionisherebyalsograntedtodistributebinaryprogramswhichdependonthispackageifthebinaryprogramdependsonamodifiedversionofthispackageyouareencouragedtopubliclyreleasethemodifiedversionofthispackagethispackageisprovidedasisandwithoutwarrantyanyexpressorimpliedwarrantiesincludingbutnotlimitedtotheimpliedwarrantiesofmerchantabilityandfitnessforaparticularpurposearedisclaimedinnoeventshalltheauthorsbeliabletoanypartyforanydirectindirectincidentalspecialexemplaryorconsequentialdamagesarisinginanywayoutoftheuseofthispackage");
  licenses[4].ln = 712;

  strcpy(licenses[5].spdx_id, "EFL-2.0");
  strcpy(licenses[5].text,"eiffelforumlicenseversion2");
  licenses[5].ln = 26;

  strcpy(licenses[6].spdx_id, "MS-RL");
  strcpy(licenses[6].text,"microsoftreciprocallicensemsrl");
  licenses[6].ln = 30;

  strcpy(licenses[7].spdx_id, "OpenSSL");
  strcpy(licenses[7].text,"thispackageisansslimplementationwrittenbyericyoungeaycryptsoftcomtheimplementationwaswrittensoastoconformwithnetscapessslthislibraryisfreeforcommercialandnoncommercialuseaslongasthefollowingconditionsareahearedtothefollowingconditionsapplytoallcodefoundinthisdistributionbeittherc4rsalhashdesetccodenotjustthesslcodethessldocumentationincludedwiththisdistributioniscoveredbythesamecopyrighttermsexceptthattheholderistimhudsontjhcryptsoftcomcopyrightremainsericyoungsandassuchanycopyrightnoticesinthecodearenottoberemovedifthispackageisusedinaproductericyoungshouldbegivenattributionastheauthorofthepartsofthelibraryusedthiscanbeintheformofatextualmessageatprogramstartuporindocumentationonlineortextualprovidedwiththepackage");
  licenses[7].ln = 724;

  strcpy(licenses[8].spdx_id, "OpenSSL");
  strcpy(licenses[8].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistribution3alladvertisingmaterialsmentioningfeaturesoruseofthissoftwaremustdisplaythefollowingacknowledgmentthisproductincludessoftwaredevelopedbytheopensslprojectforuseintheopenssltoolkithttpwwwopensslorg4thenamesopenssltoolkitandopensslprojectmustnotbeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutpriorwrittenpermissionforwrittenpermissionpleasecontactopensslcoreopensslorg5productsderivedfromthissoftwaremaynotbecalledopensslnormayopensslappearintheirnameswithoutpriorwrittenpermissionoftheopensslproject6redistributionsofanyformwhatsoevermustretainthefollowingacknowledgmentthisproductincludessoftwaredevelopedbytheo");
  licenses[8].ln = 1023;

  strcpy(licenses[9].spdx_id, "OpenSSL");
  strcpy(licenses[9].text,"openssllicense");
  licenses[9].ln = 14;

  strcpy(licenses[10].spdx_id, "ISC");
  strcpy(licenses[10].text,"isclicense");
  licenses[10].ln = 10;

  strcpy(licenses[11].spdx_id, "ISC");
  strcpy(licenses[11].text,"permissiontousecopymodifyandordistributethissoftwareforanypurposewithorwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeandthispermissionnoticeappearinallcopiesthesoftwareisprovidedasisandiscdisclaimsallwarrantieswithregardtothissoftwareincludingallimpliedwarrantiesofmerchantabilityandfitnessinnoeventshalliscbeliableforanyspecialdirectindirectorconsequentialdamagesoranydamageswhatsoeverresultingfromlossofusedataorprofitswhetherinanactionofcontractnegligenceorothertortiousactionarisingoutoforinconnectionwiththeuseorperformanceofthissoftware");
  licenses[11].ln = 556;

  strcpy(licenses[12].spdx_id, "MIT-CMU");
  strcpy(licenses[12].text,"byobtainingusingandorcopyingthissoftwareandoritsassociateddocumentationyouagreethatyouhavereadunderstoodandwillcomplywiththefollowingtermsandconditionspermissiontousecopymodifyanddistributethissoftwareanditsassociateddocumentationforanypurposeandwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeappearsinallcopiesandthatboththatcopyrightnoticeandthispermissionnoticeappearinsupportingdocumentationandthatthenameofthecopyrightholdernotbeusedinadvertisingorpublicitypertainingtodistributionofthesoftwarewithoutspecificwrittenpermissionthecopyrightholderdisclaimallwarrantieswithregardtothissoftwareincludingallimpliedwarrantiesofmerchantabilityandfitnessinnoeventshallthecopyrightholderbeliableforanyspecialindirectorconsequentialdamagesoranydamageswhatsoeverresultingfromthelossofusedataorprofitswhetherinanactionofcontractnegligenceorothertortiousactionarisingoutoforinconnectionwiththeuseorperformanceofthissoftware");
  licenses[12].ln = 927;

  strcpy(licenses[13].spdx_id, "bzip2-1.0.6");
  strcpy(licenses[13].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2theoriginofthissoftwaremustnotbemisrepresentedyoumustnotclaimthatyouwrotetheoriginalsoftwareifyouusethissoftwareinaproductanacknowledgmentintheproductdocumentationwouldbeappreciatedbutisnotrequired3alteredsourceversionsmustbeplainlymarkedassuchandmustnotbemisrepresentedasbeingtheoriginalsoftware4thenameoftheauthormaynotbeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutspecificpriorwrittenpermissionthissoftwareisprovidedbytheauthorasisandanyexpressorimpliedwarrantiesincludingbutnotlimitedtotheimpliedwarrantiesofmerchantabilityandfitnessforaparticularpurposearedisclaimedinnoeventshalltheauthorbeliableforanydirectindirectincidentalspecialexemplaryorconsequentialdamagesincludingbutnotlimitedtoprocurementofsubstitutegoodsorserviceslossofusedataorprofitsorbusinessinterruptionhowev");
  licenses[13].ln = 1023;

  strcpy(licenses[14].spdx_id, "EUPL-1.1");
  strcpy(licenses[14].text,"europeanunionpubliclicencev11");
  licenses[14].ln = 29;

  strcpy(licenses[15].spdx_id, "Qhull");
  strcpy(licenses[15].text,"thissoftwareincludesqhullfromthegeometrycenterqhulliscopyrightedasnotedaboveqhullisfreesoftwareandmaybeobtainedviahttpfromwwwqhullorgitmaybefreelycopiedmodifiedandredistributedunderthefollowingconditions");
  licenses[15].ln = 203;

  strcpy(licenses[16].spdx_id, "MPL-1.1");
  strcpy(licenses[16].text,"thecontentsofthisfilearesubjecttothemozillapubliclicenseversion11thelicenseyoumaynotusethisfileexceptincompliancewiththelicense");
  licenses[16].ln = 127;

  strcpy(licenses[17].spdx_id, "Unicode-DFS-2015");
  strcpy(licenses[17].text,"unicodeinclicenseagreementdatafilesandsoftwareunicodedatafilesincludealldatafilesunderthedirectorieshttpwwwunicodeorgpublichttpwwwunicodeorgreportsandhttpwwwunicodeorgcldrdataunicodedatafilesdonotincludepdfonlinecodechartsunderthedirectoryhttpwwwunicodeorgpublicsoftwareincludesanysourcecodepublishedintheunicodestandardorunderthedirectorieshttpwwwunicodeorgpublichttpwwwunicodeorgreportsandhttpwwwunicodeorgcldrdata");
  licenses[17].ln = 416;

  strcpy(licenses[18].spdx_id, "GPL-3.0-only");
  strcpy(licenses[18].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseversion3aspublishedbythefreesoftwarefoundation");
  licenses[18].ln = 120;

  strcpy(licenses[19].spdx_id, "GPL-3.0-only");
  strcpy(licenses[19].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundationversion3thisprogram");
  licenses[19].ln = 131;

  strcpy(licenses[20].spdx_id, "NTP");
  strcpy(licenses[20].text,"permissiontousecopymodifyanddistributethissoftwareanditsdocumentationforanypurposewithorwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeappearsinallcopiesandthatboththecopyrightnoticeandthispermissionnoticeappearinsupportingdocumentationandthatthename");
  licenses[20].ln = 263;

  strcpy(licenses[21].spdx_id, "NTP");
  strcpy(licenses[21].text,"ntplicense");
  licenses[21].ln = 10;

  strcpy(licenses[22].spdx_id, "BSD-3-Clause");
  strcpy(licenses[22].text,"northenamesofitscontributorsmaybeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutspecificpriorwrittenpermission");
  licenses[22].ln = 123;

  strcpy(licenses[23].spdx_id, "AGPL-3.0-only");
  strcpy(licenses[23].text,"thisprogramisfreesoftwareyoucanredistributeitandormodifyitunderthetermsofthegnuafferogeneralpubliclicenseaspublishedbythefreesoftwarefoundationversion3thisprogramisdistributedinthehopethatitwillbeusefulbutwithoutanywarrantywithouteventheimpliedwarrantyofmerchantabilityorfitnessforaparticularpurposeseethegnuafferogeneralpubliclicenseformoredetails");
  licenses[23].ln = 348;

  strcpy(licenses[24].spdx_id, "AGPL-3.0-only");
  strcpy(licenses[24].text,"httpwwwgnuorglicensesagpl30txt");
  licenses[24].ln = 30;

  strcpy(licenses[25].spdx_id, "IBM-pibs");
  strcpy(licenses[25].text,"thissourcecodehasbeenmadeavailabletoyoubyibmonanasisbasisanyonereceivingthissourceislicensedunderibmcopyrightstouseitinanywayheorshedeemsfitincludingcopyingitmodifyingitcompilingitandredistributingiteitherwithorwithoutmodificationsnolicenseunderibmpatentsorpatentapplicationsistobeimpliedbythecopyrightlicenseanyuserofthissoftwareshouldunderstandthatibmcannotprovidetechnicalsupportforthissoftwareandwillnotberesponsibleforanyconsequencesresultingfromtheuseofthissoftwareanypersonwhotransfersthissourcecodeoranyderivativeworkmustincludetheibmcopyrightnoticethisparagraphandtheprecedingtwoparagraphsinthetransferredsoftware");
  licenses[25].ln = 622;

  strcpy(licenses[26].spdx_id, "RPL-1.5");
  strcpy(licenses[26].text,"thereciprocalpubliclicenserplisbasedontheconceptofreciprocityorifyoupreferfairness");
  licenses[26].ln = 82;

  strcpy(licenses[27].spdx_id, "RPL-1.5");
  strcpy(licenses[27].text,"reciprocalpubliclicense15");
  licenses[27].ln = 25;

  strcpy(licenses[28].spdx_id, "bzip2-1.0.5");
  strcpy(licenses[28].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremetredistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimertheoriginofthissoftwaremustnotbemisrepresentedyoumustnotclaimthatyouwrotetheoriginalsoftwareifyouusethissoftwareinaproductanacknowledgmentintheproductdocumentationwouldbeappreciatedbutisnotrequiredalteredsourceversionsmustbeplainlymarkedassuchandmustnotbemisrepresentedasbeingtheoriginalsoftwarethenameoftheauthormaynotbeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutspecificpriorwrittenpermissionthissoftwareisprovidedbytheauthorasisandanyexpressorimpliedwarrantiesincludingbutnotlimitedtotheimpliedwarrantiesofmerchantabilityandfitnessforaparticularpurposearedisclaimedinnoeventshalltheauthorbeliableforanydirectindirectincidentalspecialexemplaryorconsequentialdamagesincludingbutnotlimitedtoprocurementofsubstitutegoodsorserviceslossofusedataorprofitsorbusinessinterruptionhoweverca");
  licenses[28].ln = 1023;

  strcpy(licenses[29].spdx_id, "AFL-2.1");
  strcpy(licenses[29].text,"licensedundertheacademicfreelicenseversion21");
  licenses[29].ln = 44;

  strcpy(licenses[30].spdx_id, "AFL-2.1");
  strcpy(licenses[30].text,"theacademicfreelicensev21");
  licenses[30].ln = 25;

  strcpy(licenses[31].spdx_id, "LGPL-2.1-only");
  strcpy(licenses[31].text,"thislibraryisfreesoftwareyoucanredistributeitandormodifyitunderthetermsofthegnulessergeneralpubliclicenseaspublishedbythefreesoftwarefoundationversion21thislibraryisdistributedinthehopethatitwillbeusefulbutwithoutanywarrantywithouteventheimpliedwarrantyofmerchantabilityorfitnessforaparticularpurposeseethegnulessergeneralpubliclicenseformoredetails");
  licenses[31].ln = 349;

  strcpy(licenses[32].spdx_id, "LGPL-2.1-only");
  strcpy(licenses[32].text,"gnulessergeneralpubliclicenseversion21february1999");
  licenses[32].ln = 50;

  strcpy(licenses[33].spdx_id, "BSD-2-Clause-Patent");
  strcpy(licenses[33].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistributionsubjecttothetermsandconditionsofthislicenseeachcopyrightholderandcontributorherebygrantstothosereceivingrightsunderthislicenseaperpetualworldwidenonexclusivenochargeroyaltyfreeirrevocableexceptforfailuretosatisfytheconditionsofthislicensepatentlicensetomakehavemadeuseoffertosellsellimportandotherwisetransferthissoftwarewheresuchlicenseappliesonlytothosepatentclaimsalreadyacquiredorhereafteracquiredlicensablebysuchcopyrightholderorcontributorthatarenecessarilyinfringedbyatheircontributionsthelicensedcopyrightsofcopyrightholdersandnoncopyrightableadditionsofcontributorsinsourceorbinaryformaloneorbcombinationoftheircontr");
  licenses[33].ln = 1023;

  strcpy(licenses[34].spdx_id, "Python-2.0");
  strcpy(licenses[34].text,"pythonsoftwarefoundationlicenseversion2");
  licenses[34].ln = 39;

  strcpy(licenses[35].spdx_id, "UPL-1.0");
  strcpy(licenses[35].text,"theabovecopyrightnoticeandeitherthiscompletepermissionnoticeorataminimumareferencetotheuplmustbeincludedinallcopiesorsubstantialportionsofthesoftware");
  licenses[35].ln = 149;

  strcpy(licenses[36].spdx_id, "UPL-1.0");
  strcpy(licenses[36].text,"theuniversalpermissivelicenseuplversion10");
  licenses[36].ln = 41;

  strcpy(licenses[37].spdx_id, "GPL-2.0-or-later");
  strcpy(licenses[37].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion2");
  licenses[37].ln = 126;

  strcpy(licenses[38].spdx_id, "CPL-1.0");
  strcpy(licenses[38].text,"commonpubliclicense");
  licenses[38].ln = 19;

  strcpy(licenses[39].spdx_id, "libtiff");
  strcpy(licenses[39].text,"permissiontousecopymodifydistributeandsellthissoftwareanditsdocumentationforanypurposeisherebygrantedwithoutfeeprovidedthatitheabovecopyrightnoticesandthispermissionnoticeappearinallcopiesofthesoftwareandrelateddocumentationandiithenamesofsamlefflerandsilicongraphicsmaynotbeusedinanyadvertisingorpublicityrelatingtothesoftwarewithoutthespecificpriorwrittenpermissionofsamlefflerandsilicongraphicsthesoftwareisprovidedasisandwithoutwarrantyofanykindexpressimpliedorotherwiseincludingwithoutlimitationanywarrantyofmerchantabilityorfitnessforaparticularpurposeinnoeventshallsamlefflerorsilicongraphicsbeliableforanyspecialincidentalindirectorconsequentialdamagesofanykindoranydamageswhatsoeverresultingfromlossofusedataorprofitswhetherornotadvisedofthepossibilityofdamageandonanytheoryofliabilityarisingoutoforinconnectionwiththeuseorperformanceofthissoftware");
  licenses[39].ln = 857;

  strcpy(licenses[40].spdx_id, "OSL-3.0");
  strcpy(licenses[40].text,"licensedundertheopensoftwarelicenseversion30");
  licenses[40].ln = 44;

  strcpy(licenses[41].spdx_id, "OSL-3.0");
  strcpy(licenses[41].text,"opensoftwarelicensev30");
  licenses[41].ln = 22;

  strcpy(licenses[42].spdx_id, "LGPL-2.1-or-later");
  strcpy(licenses[42].text,"youcanredistributeitandormodifyitunderthetermsofthegnulibrarygeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion2");
  licenses[42].ln = 133;

  strcpy(licenses[43].spdx_id, "LGPL-2.1-or-later");
  strcpy(licenses[43].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion21");
  licenses[43].ln = 127;

  strcpy(licenses[44].spdx_id, "LGPL-2.1-or-later");
  strcpy(licenses[44].text,"youcanredistributeitandormodifyitunderthetermsofthegnulessergeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion2");
  licenses[44].ln = 132;

  strcpy(licenses[45].spdx_id, "LGPL-3.0-only");
  strcpy(licenses[45].text,"thisversionofthegnulessergeneralpubliclicenseincorporatesthetermsandconditionsofversion3ofthegnugeneralpubliclicensesupplementedbytheadditionalpermissionslistedbelow");
  licenses[45].ln = 165;

  strcpy(licenses[46].spdx_id, "LGPL-3.0-only");
  strcpy(licenses[46].text,"gnulessergeneralpubliclicenseversion329june2007");
  licenses[46].ln = 47;

  strcpy(licenses[47].spdx_id, "CDDL-1.0");
  strcpy(licenses[47].text,"commondevelopmentanddistributionlicensecddl");
  licenses[47].ln = 43;

  strcpy(licenses[48].spdx_id, "Apache-1.0");
  strcpy(licenses[48].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistribution3alladvertisingmaterialsmentioningfeaturesoruseofthissoftwaremustdisplaythefollowingacknowledgmentthisproductincludessoftwaredevelopedbytheapachegroupforuseintheapachehttpserverprojecthttpwwwapacheorg4thenameapacheserverandapachegroupmustnotbeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutpriorwrittenpermissionforwrittenpermissionpleasecontactapacheapacheorg5productsderivedfromthissoftwaremaynotbecalledapachenormayapacheappearintheirnamewithoutpriorwrittenpermissionoftheapachegroup6redistributionsofanyformwhatsoevermustretainthefollowingacknowledgmentthisproductincludessoftwaredevelopedbytheapachegroupfor");
  licenses[48].ln = 1023;

  strcpy(licenses[49].spdx_id, "Apache-1.0");
  strcpy(licenses[49].text,"httpwwwapacheorglicenseslicense10");
  licenses[49].ln = 33;

  strcpy(licenses[50].spdx_id, "EPL-1.0");
  strcpy(licenses[50].text,"eclipsepubliclicensev10");
  licenses[50].ln = 23;

  strcpy(licenses[51].spdx_id, "NBPL-1.0");
  strcpy(licenses[51].text,"netbooleanpubliclicense");
  licenses[51].ln = 23;

  strcpy(licenses[52].spdx_id, "IJG");
  strcpy(licenses[52].text,"inplainenglish1wedontpromisethatthissoftwareworksbutifyoufindanybugspleaseletusknow2youcanusethissoftwareforwhateveryouwantyoudonthavetopayus3youmaynotpretendthatyouwrotethissoftwareifyouuseitinaprogramyoumustacknowledgesomewhereinyourdocumentationthatyouveusedtheijgcodeinlegalesetheauthorsmakenowarrantyorrepresentationeitherexpressorimpliedwithrespecttothissoftwareitsqualityaccuracymerchantabilityorfitnessforaparticularpurposethissoftwareisprovidedasisandyouitsuserassumetheentireriskastoitsqualityandaccuracy");
  licenses[52].ln = 514;

  strcpy(licenses[53].spdx_id, "IJG");
  strcpy(licenses[53].text,"independentjpeggrouplicense");
  licenses[53].ln = 27;

  strcpy(licenses[54].spdx_id, "BSL-1.0");
  strcpy(licenses[54].text,"permissionisherebygrantedfreeofchargetoanypersonororganizationobtainingacopyofthesoftwareandaccompanyingdocumentationcoveredbythislicensethesoftwaretousereproducedisplaydistributeexecuteandtransmitthesoftwareandtopreparederivativeworksofthesoftwareandtopermitthirdpartiestowhomthesoftwareisfurnishedtodosoallsubjecttothefollowingthecopyrightnoticesinthesoftwareandthisentirestatementincludingtheabovelicensegrantthisrestrictionandthefollowingdisclaimermustbeincludedinallcopiesofthesoftwareinwholeorinpartandallderivativeworksofthesoftwareunlesssuchcopiesorderivativeworksaresolelyintheformofmachineexecutableobjectcodegeneratedbyasourcelanguageprocessorthesoftwareisprovidedasiswithoutwarrantyofanykindexpressorimpliedincludingbutnotlimitedtothewarrantiesofmerchantabilityfitnessforaparticularpurposetitleandnoninfringementinnoeventshallthecopyrightholdersoranyonedistributingthesoftwarebeliableforanydamagesorotherliabilitywhetherincontracttortorotherwisearisingfromoutoforinconnectionwiththesoftwareortheuseorotherdealin");
  licenses[54].ln = 1023;

  strcpy(licenses[55].spdx_id, "AGPL-3.0-or-later");
  strcpy(licenses[55].text,"gnuafferogeneralpubliclicensegnuagplaspublishedbythefreesoftwarefoundationeitherversion3ofthelicenseoratyouroptionanylaterversion");
  licenses[55].ln = 129;

  strcpy(licenses[56].spdx_id, "AGPL-3.0-or-later");
  strcpy(licenses[56].text,"thisprogramisfreesoftwareyoucanredistributeitandormodifyitunderthetermsofthegnuafferogeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion3ofthelicenseoratyouroptionanylaterversion");
  licenses[56].ln = 198;

  strcpy(licenses[57].spdx_id, "MIT");
  strcpy(licenses[57].text,"thesoftwareisprovidedasiswithoutwarrantyofanykindexpressorimpliedincludingbutnotlimitedtothewarrantiesofmerchantabilityfitnessforaparticularpurposeandnoninfringementinnoeventshalltheauthorsorcopyrightholdersbeliableforanyclaimdamagesorotherliabilitywhetherinanactionofcontracttortorotherwisearisingfromoutoforinconnectionwiththesoftwareortheuseorotherdealingsinthesoftware");
  licenses[57].ln = 372;

  strcpy(licenses[58].spdx_id, "MIT");
  strcpy(licenses[58].text,"mitlicense");
  licenses[58].ln = 10;

  strcpy(licenses[59].spdx_id, "MIT");
  strcpy(licenses[59].text,"permissiontousecopymodifyanddistributethissoftwareforanypurposewithorwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeandthispermissionnoticeappearinallcopies");
  licenses[59].ln = 169;

  strcpy(licenses[60].spdx_id, "MIT");
  strcpy(licenses[60].text,"todealinthesoftwarewithoutrestrictionincludingwithoutlimitationtherightstousecopymodifymergepublishdistributesublicenseandorsellcopiesofthesoftwareandtopermitpersonstowhomthesoftwareisfurnishedtodososubjecttothefollowingconditionstheabovecopyrightnoticeandthispermissionnotice");
  licenses[60].ln = 276;

  strcpy(licenses[61].spdx_id, "MPL-2.0");
  strcpy(licenses[61].text,"thissourcecodeformissubjecttothetermsofthemozillapubliclicensev20ifacopyofthemplwasnotdistributedwiththisfileyoucanobtainoneathttpmozillaorgmpl20");
  licenses[61].ln = 145;

  strcpy(licenses[62].spdx_id, "ICU");
  strcpy(licenses[62].text,"permissionisherebygrantedfreeofchargetoanypersonobtainingacopyofthissoftwareandassociateddocumentationfilesthesoftwaretodealinthesoftwarewithoutrestrictionincludingwithoutlimitationtherightstousecopymodifymergepublishdistributeandorsellcopiesofthesoftwareandtopermitpersonstowhomthesoftwareisfurnishedtodosoprovidedthattheabovecopyrightnoticesandthispermissionnoticeappearinallcopiesofthesoftwareandthatboththeabovecopyrightnoticesandthispermissionnoticeappearinsupportingdocumentationthesoftwareisprovidedasiswithoutwarrantyofanykindexpressorimpliedincludingbutnotlimitedtothewarrantiesofmerchantabilityfitnessforaparticularpurposeandnoninfringementofthirdpartyrightsinnoeventshallthecopyrightholderorholdersincludedinthisnoticebeliableforanyclaimoranyspecialindirectorconsequentialdamagesoranydamageswhatsoeverresultingfromlossofusedataorprofitswhetherinanactionofcontractnegligenceorothertortiousactionarisingoutoforinconnectionwiththeuseorperformanceofthissoftwareexceptascontainedinthisnoticethenameofacopyrightholders");
  licenses[62].ln = 1023;

  strcpy(licenses[63].spdx_id, "ICU");
  strcpy(licenses[63].text,"iculicenseicu181andlater");
  licenses[63].ln = 24;

  strcpy(licenses[64].spdx_id, "X11");
  strcpy(licenses[64].text,"permissionisherebygrantedfreeofchargetoanypersonobtainingacopyofthissoftwareandassociateddocumentationfilesthesoftwaretodealinthesoftwarewithoutrestrictionincludingwithoutlimitationtherightstousecopymodifymergepublishdistributesublicenseandorsellcopiesofthesoftwareandtopermitpersonstowhomthesoftwareisfurnishedtodososubjecttothefollowingconditionstheabovecopyrightnoticeandthispermissionnoticeshallbeincludedinallcopiesorsubstantialportionsofthesoftwarethesoftwareisprovidedasiswithoutwarrantyofanykindexpressorimpliedincludingbutnotlimitedtothewarrantiesofmerchantabilityfitnessforaparticularpurposeandnoninfringementinnoeventshallthexconsortiumbeliableforanyclaimdamagesorotherliabilitywhetherinanactionofcontracttortorotherwisearisingfromoutoforinconnectionwiththesoftwareortheuseorotherdealingsinthesoftwareexceptascontainedinthisnoticethenameofthexconsortiumshallnotbeusedinadvertisingorotherwisetopromotethesaleuseorotherdealingsinthissoftwarewithoutpriorwrittenauthorizationfromthexconsortiumxwindowsystemisatradema");
  licenses[64].ln = 1023;

  strcpy(licenses[65].spdx_id, "X11");
  strcpy(licenses[65].text,"x11license");
  licenses[65].ln = 10;

  strcpy(licenses[66].spdx_id, "FTL");
  strcpy(licenses[66].text,"thefreetypeprojectisdistributedinseveralarchivepackagessomeofthemmaycontaininadditiontothefreetypefontenginevarioustoolsandcontributionswhichrelyonorrelatetothefreetypeprojectthislicenseappliestoallfilesfoundinsuchpackagesandwhichdonotfallundertheirownexplicitlicensethelicenseaffectsthusthefreetypefontenginethetestprogramsdocumentationandmakefilesattheveryleast");
  licenses[66].ln = 363;

  strcpy(licenses[67].spdx_id, "FTL");
  strcpy(licenses[67].text,"thefreetypeprojectlicense");
  licenses[67].ln = 25;

  strcpy(licenses[68].spdx_id, "LGPL-3.0-or-later");
  strcpy(licenses[68].text,"youcanredistributeitandormodifyitunderthetermsofthegnulessergeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion3");
  licenses[68].ln = 132;

  strcpy(licenses[69].spdx_id, "BSD-2-Clause");
  strcpy(licenses[69].text,"redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistribution");
  licenses[69].ln = 278;

  strcpy(licenses[70].spdx_id, "Apache-1.1");
  strcpy(licenses[70].text,"apachelicense11");
  licenses[70].ln = 15;

  strcpy(licenses[71].spdx_id, "Apache-1.1");
  strcpy(licenses[71].text,"httpapacheorglicenseslicense11");
  licenses[71].ln = 30;

  strcpy(licenses[72].spdx_id, "MS-PL");
  strcpy(licenses[72].text,"microsoftpubliclicense");
  licenses[72].ln = 22;

  strcpy(licenses[73].spdx_id, "GPL-2.0-only");
  strcpy(licenses[73].text,"youcanredistributeitandormodifyitunderthetermsversion2ofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundation");
  licenses[73].ln = 120;

  strcpy(licenses[74].spdx_id, "GPL-2.0-only");
  strcpy(licenses[74].text,"youcanredistributeitandormodifyitunderthetermsofversion2ofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundation");
  licenses[74].ln = 122;

  strcpy(licenses[75].spdx_id, "GPL-2.0-only");
  strcpy(licenses[75].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseversion2onlyaspublishedbythefreesoftwarefoundation");
  licenses[75].ln = 124;

  strcpy(licenses[76].spdx_id, "GPL-2.0-only");
  strcpy(licenses[76].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseversion2aspublishedbythefreesoftwarefoundation");
  licenses[76].ln = 120;

  strcpy(licenses[77].spdx_id, "GPL-2.0-only");
  strcpy(licenses[77].text,"httpwwwgnuorglicensesgpl20html");
  licenses[77].ln = 30;

  strcpy(licenses[78].spdx_id, "GPL-2.0-only");
  strcpy(licenses[78].text,"ismadeavailabletoanyonewishingtousemodifycopyorredistributeitsubjecttothetermsandconditionsofthegnugeneralpubliclicensev20");
  licenses[78].ln = 122;

  strcpy(licenses[79].spdx_id, "GPL-2.0-only");
  strcpy(licenses[79].text,"youcanredistributeitandormodifyitunderthetermsofthegnugeneralpubliclicenseaspublishedbythefreesoftwarefoundationversion2thisprogram");
  licenses[79].ln = 131;

  strcpy(licenses[80].spdx_id, "XFree86-1.1");
  strcpy(licenses[80].text,"exceptascontainedinthisnoticethenameofthexfree86projectincshallnotbeusedinadvertisingorotherwisetopromotethesaleuseorotherdealingsinthissoftwarewithoutpriorwrittenauthorizationfromthexfree86projectinc");
  licenses[80].ln = 200;

  strcpy(licenses[81].spdx_id, "XFree86-1.1");
  strcpy(licenses[81].text,"xfree86license");
  licenses[81].ln = 14;

  strcpy(licenses[82].spdx_id, "PostgreSQL");
  strcpy(licenses[82].text,"permissiontousecopymodifyanddistributethissoftwareanditsdocumentationforanypurposewithoutfeeandwithoutawrittenagreementisherebygrantedprovidedthattheabovecopyrightnoticeandthisparagraphandthefollowingtwoparagraphsappearinallcopiesinnoeventshall");
  licenses[82].ln = 244;

  strcpy(licenses[83].spdx_id, "PostgreSQL");
  strcpy(licenses[83].text,"thissoftwareisreleasedunderthepostgresqllicence");
  licenses[83].ln = 47;

  strcpy(licenses[84].spdx_id, "Apache-2.0");
  strcpy(licenses[84].text,"httpwwwapacheorglicenseslicense20");
  licenses[84].ln = 33;

  strcpy(licenses[85].spdx_id, "Apache-2.0");
  strcpy(licenses[85].text,"apachelicenseversion20");
  licenses[85].ln = 22;

  strcpy(licenses[86].spdx_id, "MirOS");
  strcpy(licenses[86].text,"providedthatthesetermsanddisclaimerandallcopyrightnoticesareretainedorreproducedinanaccompanyingdocumentpermissionisgrantedtodealinthisworkwithoutrestrictionincludingunlimitedrightstousepubliclyperformdistributesellmodifymergegiveawayorsublicencethisworkisprovidedasisandwithoutwarrantyofanykindtotheutmostextentpermittedbyapplicablelawneitherexpressnorimpliedwithoutmaliciousintentorgrossnegligenceinnoeventmayalicensorauthororcontributorbeheldliableforindirectdirectotherdamagelossorotherissuesarisinginanywayoutofdealingintheworkevenifadvisedofthepossibilityofsuchdamageorexistenceofadefectexceptproventhatitresultsoutofsaidpersonsimmediatefaultwhenusingtheworkasintended");
  licenses[86].ln = 674;

  strcpy(licenses[87].spdx_id, "FSFULLR");
  strcpy(licenses[87].text,"freesoftwarefoundationgivesunlimitedpermissiontocopyandordistributeitwithorwithoutmodificationsaslongasthisnoticeispreserved");
  licenses[87].ln = 124;

  strcpy(licenses[88].spdx_id, "WTFPL");
  strcpy(licenses[88].text,"dowhatthefuckyouwanttopubliclicense");
  licenses[88].ln = 35;

  strcpy(licenses[89].spdx_id, "Artistic-1.0-Perl");
  strcpy(licenses[89].text,"artisticlicense10");
  licenses[89].ln = 17;

  strcpy(licenses[90].spdx_id, "Artistic-1.0-Perl");
  strcpy(licenses[90].text,"preambletheintentofthisdocumentistostatetheconditionsunderwhichapackagemaybecopiedsuchthatthecopyrightholdermaintainssomesemblanceofartisticcontroloverthedevelopmentofthepackagewhilegivingtheusersofthepackagetherighttouseanddistributethepackageinamoreorlesscustomaryfashionplustherighttomakereasonablemodificationsdefinitionspackagereferstothecollectionoffilesdistributedbythecopyrightholderandderivativesofthatcollectionoffilescreatedthroughtextualmodificationstandardversionreferstosuchapackageifithasnotbeenmodifiedorhasbeenmodifiedinaccordancewiththewishesofthecopyrightholderasspecifiedbelowcopyrightholderiswhoeverisnamedinthecopyrightorcopyrightsforthepackageyouisyouifyourethinkingaboutcopyingordistributingthispackagereasonablecopyingfeeiswhateveryoucanjustifyonthebasisofmediacostduplicationchargestimeofpeopleinvolvedandsoonyouwillnotberequiredtojustifyittothecopyrightholderbutonlytothecomputingcommunityatlargeasamarketthatmustbearthefeefreelyavailablemeansthatnofeeischargedfortheitemitselfthoughtheremaybefee");
  licenses[90].ln = 1023;

  strcpy(licenses[91].spdx_id, "AFL-2.0");
  strcpy(licenses[91].text,"theacademicfreelicensev20");
  licenses[91].ln = 25;

  strcpy(licenses[92].spdx_id, "AFL-2.0");
  strcpy(licenses[92].text,"licensedundertheacademicfreelicenseversion20");
  licenses[92].ln = 44;

  strcpy(licenses[93].spdx_id, "curl");
  strcpy(licenses[93].text,"permissiontousecopymodifyanddistributethissoftwareforanypurposewithorwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeandthispermissionnoticeappearinallcopiesthesoftwareisprovidedasiswithoutwarrantyofanykindexpressorimpliedincludingbutnotlimitedtothewarrantiesofmerchantabilityfitnessforaparticularpurposeandnoninfringementofthirdpartyrightsinnoeventshalltheauthorsorcopyrightholdersbeliableforanyclaimdamagesorotherliabilitywhetherinanactionofcontracttortorotherwisearisingfromoutoforinconnectionwiththesoftwareortheuseorotherdealingsinthesoftwareexceptascontainedinthisnoticethenameofacopyrightholdershallnotbeusedinadvertisingorotherwisetopromotethesaleuseorotherdealingsinthissoftwarewithoutpriorwrittenauthorizationofthecopyrightholder");
  licenses[93].ln = 751;

  strcpy(licenses[94].spdx_id, "HPND");
  strcpy(licenses[94].text,"permissiontousecopymodifyanddistributethissoftwareanditsdocumentationforanypurposeandwithoutfeeisherebygrantedprovidedthattheabovecopyrightnoticeappearinallcopiesandthatboththatthecopyrightnoticeandthispermissionnoticeappearinsupportingdocumentationandthatthenameofcopyrightholderorrelatedentitiesnotbeusedinadvertisingorpublicitypertainingtodistributionofthesoftwarewithoutspecificwrittenpriorpermissioncopyrightholdermakesnorepresentationsaboutthesuitabilityofthissoftwareforanypurposeitisprovidedasiswithoutexpressorimpliedwarrantycopyrightholderdisclaimsallwarrantieswithregardtothissoftwareincludingallimpliedwarrantiesofmerchantabilityandfitnessinnoeventshallcopyrightholderbeliableforanyspecialindirectorconsequentialdamagesoranydamageswhatsoeverresultingfromlossofusedataorprofitswhetherinanactionofcontractnegligenceorothertortiousactionarisingoutoforinconnectionwiththeuseorperformanceofthissoftware");
  licenses[94].ln = 909;

  strcpy(licenses[95].spdx_id, "HPND");
  strcpy(licenses[95].text,"historicalpermissionnoticeanddisclaimer");
  licenses[95].ln = 39;

  strcpy(licenses[96].spdx_id, "GPL-3.0-or-later");
  strcpy(licenses[96].text,"youcanredistributeitandormodifyitunderthetermsofthegnulessergeneralpubliclicenseaspublishedbythefreesoftwarefoundationeitherversion3");
  licenses[96].ln = 132;

  strcpy(licenses[97].spdx_id, "BSD-4-Clause");
  strcpy(licenses[97].text,"redistributionanduseinsourceandbinaryformswithorwithoutmodificationarepermittedprovidedthatthefollowingconditionsaremet1redistributionsofsourcecodemustretaintheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimer2redistributionsinbinaryformmustreproducetheabovecopyrightnoticethislistofconditionsandthefollowingdisclaimerinthedocumentationandorothermaterialsprovidedwiththedistribution3alladvertisingmaterialsmentioningfeaturesoruseofthissoftwaremustdisplaythefollowingacknowledgementthisproductincludessoftwaredevelopedbytheorganization4neitherthenameofthecopyrightholdernorthenamesofitscontributorsmaybeusedtoendorseorpromoteproductsderivedfromthissoftwarewithoutspecificpriorwrittenpermissionthissoftwareisprovidedbycopyrightholderasisandanyexpressorimpliedwarrantiesincludingbutnotlimitedtotheimpliedwarrantiesofmerchantabilityandfitnessforaparticularpurposearedisclaimedinnoeventshallcopyrightholderbeliableforanydirectindirectincidentalspecialexemplaryorconsequentialdamagesincludingbutnotlimitedtoprocur");
  licenses[97].ln = 1023;

  strcpy(licenses[98].spdx_id, "Zlib");
  strcpy(licenses[98].text,"1theoriginofthissoftwaremustnotbemisrepresentedyoumustnotclaimthatyouwrotetheoriginalsoftwareifyouusethissoftwareinaproductanacknowledgmentintheproductdocumentationwouldbeappreciatedbutisnotrequired2alteredsourceversionsmustbeplainlymarkedassuchandmustnotbemisrepresentedasbeingtheoriginalsoftware3thisnoticemaynotberemovedoralteredfromanysourcedistribution");
  licenses[98].ln = 357;

  strcpy(licenses[99].spdx_id, "MPL-2.0-no-copyleft-exception");
  strcpy(licenses[99].text,"33distributionofalargerworkyoumaycreateanddistributealargerworkundertermsofyourchoiceprovidedthatyoualsocomplywiththerequirementsofthislicenseforthecoveredsoftwareifthelargerworkisacombinationofcoveredsoftwarewithaworkgovernedbyoneormoresecondarylicensesandthecoveredsoftwareisnotincompatiblewithsecondarylicensesthislicensepermitsyoutoadditionallydistributesuchcoveredsoftwareunderthetermsofsuchsecondarylicensessothattherecipientofthelargerworkmayattheiroptionfurtherdistributethecoveredsoftwareunderthetermsofeitherthislicenseorsuchsecondarylicenses");
  licenses[99].ln = 552;

  strcpy(licenses[100].spdx_id, "zlib-acknowledgement");
  strcpy(licenses[100].text,"thissoftwareisprovidedasiswithoutanyexpressorimpliedwarrantyinnoeventwilltheauthorsbeheldliableforanydamagesarisingfromtheuseofthissoftwarepermissionisgrantedtoanyonetousethissoftwareforanypurposeincludingcommercialapplicationsandtoalteritandredistributeitfreelysubjecttothefollowingrestrictions1theoriginofthissoftwaremustnotbemisrepresentedyoumustnotclaimthatyouwrotetheoriginalsoftwareifyouusethissoftwareinaproductanacknowledgmentseethefollowingintheproductdocumentationisrequiredportionscopyrightc20022007charliepooleorcopyrightc20022004jameswnewkirkmichaelctwoalexeiavorontsovorcopyrightc20002002philipacraig2alteredsourceversionsmustbeplainlymarkedassuchandmustnotbemisrepresentedasbeingtheoriginalsoftware3thisnoticemaynotberemovedoralteredfromanysourcedistribution");
  licenses[100].ln = 773;

  strcpy(licenses[101].spdx_id, "CC0-1.0");
  strcpy(licenses[101].text,"cc010universal");
  licenses[101].ln = 14;

  strcpy(licenses[102].spdx_id, "IPL-1.0");
  strcpy(licenses[102].text,"ibmpubliclicense");
  licenses[102].ln = 16;


  return 103;
}
